language: python
python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master

install:
  - if [ -f requirements.txt ]; then pip install -r requirements.txt ; fi
  - pip install flake8

script: flake8 ./pytest_idapro --show-source --statistics
