language: python
python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master

install:
  - wget "https://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh" -O miniconda.sh ;
  - bash ./miniconda.sh -b -p "${HOME}/miniconda" ;
  - export PATH=${HOME}/miniconda/bin:$PATH ;
  - conda info -a ;
  - conda install --yes python=${TRAVIS_PYTHON_VERSION} pyqt ;
  - pip install flake8 pytest

script:
  - flake8 ./pytest_idapro --show-source --statistics
  - pip install -e .
  - pytest ./pytest_idapro ./tests
